---
title: "Schedule"
author: "Davi Moreira"
date-modified: "last-modified"
date: "2024-05-15"
date-format: "MMM D, YYYY"
# listing:
#   - id: schedule
#     contents:
#       - topics/topic-*.qmd
#     type: table
#     fields: [week, title, subtitle, date]
#     field-display-names:
#       week: "Week"
#       title: "Topic"
#       description: "Dates"
#       subtitle: "Description"
#     date-format: "MMMM DD, YYYY to MMMM DD, YYYY"
#     sort: [filename]
#     sort-ui: false
#     filter-ui: false
 #tbl-colwidths: [5,20,50,25]
editor: visual
---

| Week    | Topic                                              | Title                          | Date    |
|:------------|:-----------------------------|:----------------|:------------|
| Week 01 | [Topic 01](./topics-pages/page-topic-01.qmd)       | Introduction and Set up        | May 21  |
| Week 01 | [Topic 02](./topics-pages/page-topic-02.qmd) | Computational Literacy         | May 23  |
| Week 02 | [Topic 03](./topics-pages/page-topic-03.qmd) | Command Line                   | May 28  |
| Week 02 | [Topic 03](./topics-pages/page-topic-03.qmd) | Command Line                   | May 30  |
| Week 03 | [Topic 04](./topics-pages/page-topic-04.qmd) | Version Control                | June 4  |
| Week 03 | [Topic 04](./topics-pages/page-topic-04.qmd) | Version Control                | June 6  |
| Week 04 | [Topic 04](./topics-pages/page-topic-04.qmd) | Version Control              | June 11 |
| Week 04 | [Topic 05](./topics-pages/page-topic-05.qmd) | Python essentials              | June 13 |
| Week 05 | [Topic 06](./topics-pages/page-topic-06.qmd) | Algorithms and Data Structures | June 18 |
| Week 05 | [Topic 06](./topics-pages/page-topic-06.qmd) | Algorithms and Data Structures | June 20 |
| Week 06 | [Topic 06](./topics-pages/page-topic-06.qmd) | Algorithms and Data Structures | June 25 |
